export { default as Login } from './Auth/Login/Login';
export { default as Register } from './Auth/Register/Register';
export { default as Home } from './Home/Home';
export { default as Orders } from './Client/Orders/Orders';
export { default as OrderDetail } from './Client/OrderDetail/OrderDetail';
export { default as Admin } from './Admin/Admin';
export { default as Cart } from './Cart/Cart';
export { default as ProductDetail } from './Client/ProductDetail/ProductDetail';
export { default as Profile } from './Client/Profile/Profile';
export { Delivery, DeliveryOrders } from './Delivery';
export { default as Cook } from './Cook/Cook';
export { default as CookOrders } from './Cook/CookOrders/CookOrders'; 